
fit_Debye: fit_Debye.cc
	g++ -g -I /usr/local/include fit_Debye.cc -o fit_Debye -L/usr/local -lgsl -lgslcblas

fit_Debye2: fit_Debye2.cc
	g++ -g -I /usr/local/include fit_Debye2.cc -o fit_Debye2 -L/usr/local -lgsl -lgslcblas

